### ISSUE TITLE
unnest broken?

### ISSUE THREAD

**Issue by JoakimWeill** [nacnudus/google-location-coronavirus#1]
Hello, thanks for this code!

I can't unnest the list of fs::path on my computer, is this a package version issue? I get this error:

`df_trends <-
  df %>%
  mutate(svg_path = map(file_path, pdf_to_svg)) %>%
  unnest(svg_path)'
Error: Can't cast `svg_path$svg_path` <fs_path> to `svg_path$svg_path` <fs_path>.

**Comment by nacnudus** [comment]
I think I had this problem and it was fixed by upgrading `fs` or `dplyr` or `tidyr` or `purrr`.  Sorry I can't be more specific than that.

**Comment by MatthieuStigler** [comment]
I have the same problem! Is it possible that unnest() does not unpack well svg_path? What are these?

Converting to character seems to do the trick:

```
df %>% 
mutate(svg_path = map(file_path, ~enframe(pdf_to_svg(.), name = NULL, value = "svg_path") %>% 
                          mutate(svg_path=as.character(svg_path)))) %>% 
 unnest(svg_path)
```

**Comment by JoakimWeill** [comment]
Updating the packages didn't solve the issue, but Matthieu's solution works!
